### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by zbalkan** [determ1ne/Numlock-Indicator#1]
I tried to use your program on ReactOS. At first, I thought it is about ReactOS and created an [issue](https://jira.reactos.org/browse/CORE-16639). But it turned out to be that the issue is about the code.

As Mark Jansen pointed out, the issue is in memory allocation of your code. Zeroing the allocated memory before using is advised by him.

**Comment by determ1ne** [comment]
Merged #2
